function[random_train] = get_random_data()
random_train = {
              
              '..\random_data\random1.wav'; ...
              '..\random_data\random2.wav'; ...
              '..\random_data\random3.wav'; ...
              '..\random_data\random4.wav'; ...
              '..\random_data\random5.wav'; ...
              '..\random_data\random6.wav'; ...
              '..\random_data\random7.wav'; ...
              '..\random_data\random8.wav'; ...
              '..\random_data\random9.wav'; ...
              '..\random_data\random10.wav'; ...
              '..\random_data\random11.wav'; ...
              '..\random_data\random12.wav'; ...
              '..\random_data\random13.wav'; ...
              '..\random_data\random14.wav'; ...
              '..\random_data\random15.wav'; ...
              '..\random_data\random16.wav'; ...
              '..\random_data\random17.wav'; ...
              '..\random_data\random18.wav'; ...
              '..\random_data\random19.wav'; ...
              '..\random_data\random20.wav'; ...
              '..\random_data\random21.wav'; ...
              '..\random_data\random22.wav'; ...
              '..\random_data\random23.wav'; ...
              '..\random_data\random24.wav'; ...
              '..\random_data\random25.wav'; ...
};
random_train = char(random_train);
end