function[random_train] = get_horn_data()
random_train = {
              
              '..\random_data\silence1.wav'; ...
              '..\random_data\silence2.wav'; ...
              '..\random_data\silence3.wav'; ...
              '..\random_data\silence4.wav'; ...
              '..\random_data\silence5.wav'; ...
              '..\random_data\silence6.wav'; ...
              '..\random_data\silence7.wav'; ...
              '..\random_data\silence8.wav'; ...
              '..\random_data\silence9.wav'; ...
              '..\random_data\silence10.wav'; ...
              '..\random_data\silence11.wav'; ...
              '..\random_data\silence12.wav'; ...
              '..\random_data\silence13.wav'; ...
              '..\random_data\silence14.wav'; ...
              '..\random_data\silence15.wav'; ...
              '..\random_data\silence16.wav'; ...
              '..\random_data\silence17.wav'; ...
              '..\random_data\silence18.wav'; ...
              '..\random_data\silence19.wav'; ...
              '..\random_data\silence20.wav'; ...
              '..\random_data\silence21.wav'; ...
              '..\random_data\silence22.wav'; ...
              '..\random_data\silence23.wav'; ...
              '..\random_data\silence24.wav'; ...
              '..\random_data\silence25.wav'; ...
};
random_train = char(random_train);
end