function[sound_train] = get_horn_data()

sound_train = {
              
              '..\horn_data\horn1.wav'; ...
              '..\horn_data\horn2.wav'; ...
              '..\horn_data\horn3.wav'; ...
              '..\horn_data\horn4.wav'; ...
              '..\horn_data\horn5.wav'; ...
              '..\horn_data\horn6.wav'; ...
              '..\horn_data\horn7.wav'; ...
              '..\horn_data\horn8.wav'; ...
              '..\horn_data\horn9.wav'; ...
              '..\horn_data\horn10.wav'; ...
              '..\horn_data\horn11.wav'; ...
              '..\horn_data\horn12.wav'; ...
              '..\horn_data\horn13.wav'; ...
              '..\horn_data\horn14.wav'; ...
              '..\horn_data\horn15.wav'; ...
              '..\horn_data\horn16.wav'; ...
              '..\horn_data\horn17.wav'; ...
              '..\horn_data\horn18.wav'; ...
              '..\horn_data\horn19.wav'; ...
              '..\horn_data\horn20.wav'; ...
              '..\horn_data\horn21.wav'; ...
              '..\horn_data\horn22.wav'; ...
              '..\horn_data\horn23.wav'; ...
              '..\horn_data\horn24.wav'; ... 
              '..\horn_data\horn25.wav'; ...
              '..\horn_data\horn26.wav'; ...
              '..\horn_data\horn27.wav'; ...
              '..\horn_data\horn28.wav'; ...
              '..\horn_data\horn29.wav'; ...
              '..\horn_data\horn30.wav'; ...
              '..\horn_data\horn31.wav'; ...
              '..\horn_data\horn32.wav'; ...
              '..\horn_data\horn33.wav'; ...
              '..\horn_data\horn34.wav'; ...
              '..\horn_data\horn35.wav'; ...
              '..\horn_data\horn36.wav'; ...
              '..\horn_data\horn37.wav'; ...
              '..\horn_data\horn38.wav'; ...
              '..\horn_data\horn39.wav'; ...
              '..\horn_data\horn40.wav'; ...
              '..\horn_data\horn41.wav'; ...
              '..\horn_data\horn42.wav'; ...
              '..\horn_data\horn43.wav'; ...
              '..\horn_data\horn44.wav'; ...
              '..\horn_data\horn45.wav'; ...
              '..\horn_data\horn46.wav'; ...
              '..\horn_data\horn47.wav'; ...
              '..\horn_data\horn48.wav'; ...
              '..\horn_data\horn49.wav'; ...
              '..\horn_data\horn50.wav'; ...
              '..\horn_data\horn51.wav'; ...
} ;

sound_train = char(sound_train);
end