function[test_data] = get_test_data()
test_data = {
              '..\testing_data\realhorn001.wav'; ...
              '..\testing_data\realhorn002.wav'; ...
              '..\testing_data\realhorn003.wav'; ...
              '..\testing_data\realhorn004.wav'; ...
              '..\testing_data\realhorn005.wav'; ...
              '..\testing_data\realhorn006.wav'; ...
              '..\testing_data\realhorn007.wav'; ...
              '..\testing_data\realhorn008.wav'; ...
              '..\testing_data\realhorn009.wav'; ...
              '..\testing_data\realambient001.wav'; ...
              '..\testing_data\realambient002.wav'; ...
              '..\testing_data\realambient003.wav'; ...
              '..\testing_data\realambient004.wav'; ...
              '..\testing_data\realambient005.wav'; ...
              '..\testing_data\realambient006.wav'; ...
              '..\testing_data\realambient007.wav'; ...
    
};
test_data = char(test_data);
end