function[ambUnclipped_data] = get_ambUnclipped_data()

ambUnclipped_data = {
              '.\SoundData\Ambience\ambUnclipped (1).wav';...
              '.\SoundData\Ambience\ambUnclipped (2).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (3).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (4).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (5).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (6).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (7).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (8).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (9).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (10).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (11).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (12).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (13).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (14).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (15).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (16).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (17).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (18).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (19).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (20).wav'; ...
              '.\SoundData\Ambience\ambUnclipped (21).wav'; ...
    };

ambUnclipped_data = char(ambUnclipped_data);

end