function[cryUnclipped_data] = get_cryUnclipped_data()

cryUnclipped_data = {
                '.\SoundData\BabyCry\baby-crying-01.wav';...
                '.\SoundData\BabyCry\baby-crying-02.wav';...
                '.\SoundData\BabyCry\baby-crying-03.wav';...
                '.\SoundData\BabyCry\baby-crying-04.wav';...
                '.\SoundData\BabyCry\baby-crying-05.wav';...
                '.\SoundData\BabyCry\baby-crying-06.wav';...
                '.\SoundData\BabyCry\baby-crying-07.wav';...
    };

cryUnclipped_data = char(cryUnclipped_data);

end