function[sound_horn_files] = get_hornUnclipped_data()

sound_horn_files = {
              '.\SoundData\Horns\hornUnclipped (1).wav';...
              '.\SoundData\Horns\hornUnclipped (2).wav'; ...
              '.\SoundData\Horns\hornUnclipped (3).wav'; ...
              '.\SoundData\Horns\hornUnclipped (4).wav'; ...
              '.\SoundData\Horns\hornUnclipped (5).wav'; ...
              '.\SoundData\Horns\hornUnclipped (6).wav'; ...
              '.\SoundData\Horns\hornUnclipped (7).wav'; ...
              '.\SoundData\Horns\hornUnclipped (8).wav'; ...
              '.\SoundData\Horns\hornUnclipped (9).wav'; ...
              '.\SoundData\Horns\hornUnclipped (10).wav'; ...
              '.\SoundData\Horns\hornUnclipped (11).wav'; ...
              '.\SoundData\Horns\hornUnclipped (12).wav'; ...
              '.\SoundData\Horns\hornUnclipped (13).wav'; ...
              '.\SoundData\Horns\hornUnclipped (14).wav'; ...
              %'.\SoundData\Horns\hornUnclipped (15).wav'; ...
              '.\SoundData\Horns\hornUnclipped (16).wav'; ...
              '.\SoundData\Horns\hornUnclipped (17).wav'; ...
              '.\SoundData\Horns\hornUnclipped (18).wav'; ...
              '.\SoundData\Horns\hornUnclipped (19).wav'; ...
              '.\SoundData\Horns\hornUnclipped (20).wav'; ...
              '.\SoundData\Horns\hornUnclipped (21).wav'; ...
              '.\SoundData\Horns\hornUnclipped (22).wav'; ...
              '.\SoundData\Horns\hornUnclipped (23).wav'; ...
              '.\SoundData\Horns\hornUnclipped (24).wav'; ... 
              '.\SoundData\Horns\hornUnclipped (25).wav'; ...
              '.\SoundData\Horns\hornUnclipped (26).wav'; ...
              '.\SoundData\Horns\hornUnclipped (27).wav'; ...
              '.\SoundData\Horns\hornUnclipped (28).wav'; ...
              '.\SoundData\Horns\hornUnclipped (29).wav'; ...
              '.\SoundData\Horns\hornUnclipped (30).wav'; ...
              '.\SoundData\Horns\hornUnclipped (31).wav'; ...
              '.\SoundData\Horns\hornUnclipped (32).wav'; ...
              %'.\SoundData\Horns\hornUnclipped (33).wav'; ...
              '.\SoundData\Horns\hornUnclipped (34).wav'; ...
              '.\SoundData\Horns\hornUnclipped (35).wav'; ...
              '.\SoundData\Horns\hornUnclipped (36).wav'; ...
              '.\SoundData\Horns\hornUnclipped (37).wav'; ...
              '.\SoundData\Horns\hornUnclipped (38).wav'; ...
              '.\SoundData\Horns\hornUnclipped (39).wav'; ...
              '.\SoundData\Horns\hornUnclipped (40).wav'; ...
              '.\SoundData\Horns\hornUnclipped (41).wav'; ...
              '.\SoundData\Horns\hornUnclipped (42).wav'; ...
              '.\SoundData\Horns\hornUnclipped (43).wav'; ...
              '.\SoundData\Horns\hornUnclipped (44).wav'; ...
              '.\SoundData\Horns\hornUnclipped (45).wav'; ...
              '.\SoundData\Horns\hornUnclipped (46).wav'; ...
              '.\SoundData\Horns\hornUnclipped (47).wav'; ...
              '.\SoundData\Horns\hornUnclipped (48).wav'; ...
              '.\SoundData\Horns\hornUnclipped (49).wav'; ...
              '.\SoundData\Horns\hornUnclipped (50).wav'; ...
              '.\SoundData\Horns\hornUnclipped (51).wav'; ...
              '.\SoundData\Horns\hornUnclipped (52).wav'; ...
              '.\SoundData\Horns\hornUnclipped (53).wav'; ...
              '.\SoundData\Horns\hornUnclipped (54).wav'; ...
              '.\SoundData\Horns\hornUnclipped (55).wav'; ...
    };


sound_horn_files = char(sound_horn_files);
end