function [newData1] = importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 18-Feb-2017 15:27:36

% Import the file
newData1 = load('-mat', fileToRead1);

